import type { Metadata } from 'next'
import { LayoutProvider } from '@/components/layouts/layout-provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function AdminLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (<LayoutProvider>{children}</LayoutProvider>)
}
