import { Internship } from './types'

export const internshipsData: Internship[] = [
	{
		id: 'TT001',
		title: 'Thực tập phát triển Web tại FPT Software',
		student: 'Nguyễn Thị A',
		studentId: '20210001',
		company: 'FPT Software',
		position: 'Frontend Developer',
		supervisor: 'ThS. Trần Văn B',
		companySupervisor: 'Nguyễn Đức C',
		status: 'IN_PROGRESS',
		startDate: '2024-06-01',
		endDate: '2024-08-30',
		location: 'Hà Nội',
		salary: '5,000,000 VNĐ',
		rating: 4.5,
	},
	{
		id: 'TT002',
		title: 'Thực tập Data Science tại Viettel',
		student: 'Lê Văn D',
		studentId: '20210002',
		company: 'Viettel Digital',
		position: 'Data Analyst',
		supervisor: 'TS. Phạm Thị E',
		companySupervisor: 'Hoàng Văn F',
		status: 'COMPLETED',
		startDate: '2024-05-15',
		endDate: '2024-08-15',
		location: 'TP.HCM',
		salary: '6,000,000 VNĐ',
		rating: 5.0,
	},
	{
		id: 'TT003',
		title: 'Thực tập Mobile App tại VNG Corporation',
		student: 'Trần Thị G',
		studentId: '20210003',
		company: 'VNG Corporation',
		position: 'Mobile Developer',
		supervisor: 'ThS. Vũ Minh H',
		companySupervisor: 'Đỗ Thị I',
		status: 'PENDING_EVALUATION',
		startDate: '2024-06-15',
		endDate: '2024-09-15',
		location: 'TP.HCM',
		salary: '7,000,000 VNĐ',
		rating: 0,
	},
	{
		id: 'TT004',
		title: 'Thực tập DevOps tại TechComBank',
		student: 'Bùi Văn K',
		studentId: '20210004',
		company: 'Techcombank',
		position: 'DevOps Engineer',
		supervisor: 'TS. Ngô Thị L',
		companySupervisor: 'Phan Văn M',
		status: 'APPROVED',
		startDate: '2024-07-01',
		endDate: '2024-09-30',
		location: 'Hà Nội',
		salary: '8,000,000 VNĐ',
		rating: 0,
	},
	{
		id: 'TT005',
		title: 'Thực tập AI/ML tại VNPT Technology',
		student: 'Đinh Thị N',
		studentId: '20210005',
		company: 'VNPT Technology',
		position: 'AI Engineer',
		supervisor: 'PGS. Lê Văn O',
		companySupervisor: 'Trịnh Thị P',
		status: 'CANCELLED',
		startDate: '2024-06-01',
		endDate: '2024-08-31',
		location: 'Đà Nẵng',
		salary: '6,500,000 VNĐ',
		rating: 0,
	},
]

export function findInternshipById(id: string) {
	return internshipsData.find(internship => internship.id === id)
} 