import { User } from './types'

export const users: User[] = [
	{
		id: 'USR001',
		name: 'Trần Thị Admin',
		email: 'admin@university.edu.vn',
		avatar: '/avatars/01.png',
		role: 'ADMIN',
		status: 'ACTIVE',
		department: 'Phòng Đào tạo',
		lastLogin: '2024-10-26T10:00:00Z',
		thesesManaged: 156,
		internshipsSupervised: 89,
	},
	{
		id: 'USR002',
		name: 'Nguyễn Văn Giảng Viên',
		email: 'lecturer.nguyen@university.edu.vn',
		avatar: '/avatars/02.png',
		role: 'LECTURER',
		status: 'ACTIVE',
		department: 'Công nghệ thông tin',
		lastLogin: '2024-10-26T09:30:00Z',
		thesesManaged: 12,
		internshipsSupervised: 5,
	},
	{
		id: 'USR003',
		name: 'Lê Thị Sinh Viên',
		email: 'student.le@student.university.edu.vn',
		avatar: '/avatars/03.png',
		role: 'STUDENT',
		status: 'ACTIVE',
		department: 'Công nghệ thông tin',
		studentId: '20201234',
		lastLogin: '2024-10-25T15:20:00Z',
		thesesManaged: 1,
		internshipsSupervised: 1,
	},
	{
		id: 'USR004',
		name: 'Phạm Văn Doanh Nghiệp',
		email: 'hr@fpt.com.vn',
		avatar: '/avatars/04.png',
		role: 'BUSINESS_REP',
		status: 'ACTIVE',
		department: 'Đối ngoại',
		company: 'FPT Software',
		lastLogin: '2024-10-24T11:00:00Z',
		thesesManaged: 0,
		internshipsSupervised: 15,
	},
    {
		id: 'USR005',
		name: 'Hoàng Văn Giảng Viên',
		email: 'lecturer.hoang@university.edu.vn',
		avatar: '/avatars/05.png',
		role: 'LECTURER',
		status: 'INACTIVE',
		department: 'Kinh tế',
		lastLogin: '2024-08-15T11:00:00Z',
		thesesManaged: 8,
		internshipsSupervised: 3,
	},
    {
		id: 'USR006',
		name: 'Đặng Thị Sinh Viên',
		email: 'student.dang@student.university.edu.vn',
		avatar: '/avatars/06.png',
		role: 'STUDENT',
		status: 'PENDING',
		department: 'Quản trị Kinh doanh',
        studentId: '20215678',
		lastLogin: '2024-10-26T12:00:00Z',
		thesesManaged: 0,
		internshipsSupervised: 0,
	},
] 

export const findUserById = (id: string) => {
	return users.find(user => user.id === id)
} 