import {
	Home,
	LineChart,
	Users,
	BookOpen,
	Briefcase,
	Settings,
	BarChart,
	Building2,
	Library,
	Shield,
	Menu as MenuIcon,
	File,
	Folder,
	Link as LinkIcon,
	User,
	Calendar,
	CalendarDays,
	GraduationCap,
	FileText,
	UserCheck,
	Clock,
	ChevronRight,
	Database,
	Globe,
	Mail,
	Phone,
	MapPin,
	Star,
	Heart,
	Search,
	Filter,
	Plus,
	Edit,
	Trash2,
	Save,
	X,
	Check,
	AlertCircle,
	Info,
	HelpCircle,
	Eye,
	EyeOff,
	Download,
	Upload,
	Share,
	Copy,
	Bookmark,
	Tag,
	Bell,
	Activity,
	TrendingUp,
	Award,
	Target,
	Zap,
	Layers,
	Grid,
	List,
	Archive,
	Inbox,
	Send,
	MessageCircle,
	Video,
	Image,
	Music,
	Play,
	Pause,
	Volume2,
	VolumeX,
	Wifi,
	WifiOff,
	Battery,
	BatteryLow,
	Bluetooth,
	Camera,
	Mic,
	MicOff,
	Monitor,
	Smartphone,
	Tablet,
	Laptop,
	Server,
	CloudIcon as Cloud,
	Lock,
	Unlock,
	Key,
	LogIn,
	LogOut,
	UserPlus,
	UserMinus,
	UserX,
	CreditCard,
	DollarSign,
	ShoppingCart,
	Package,
	Truck,
	Map,
	Navigation,
	Compass,
	Flag,
	MessageSquare,
	Timer,
	Sun,
	Moon,
	CloudDrizzle,
	CloudRain,
	CloudSnow,
	Wind,
	Thermometer,
	Umbrella,
	Snowflake,
	type LucideIcon,
} from 'lucide-react'

// Map icon names to actual icon components
export const iconMap: Record<string, LucideIcon> = {
	// Main navigation icons
	home: Home,
	dashboard: Home,
	'line-chart': LineChart,
	lineChart: LineChart,
	analytics: LineChart,
	users: Users,
	user: User,
	'book-open': BookOpen,
	bookOpen: BookOpen,
	book: BookOpen,
	thesis: BookOpen,
	briefcase: Briefcase,
	internship: Briefcase,
	work: Briefcase,
	settings: Settings,
	'bar-chart': BarChart,
	barChart: BarChart,
	reports: BarChart,
	building2: Building2,
	building: Building2,
	partners: Building2,
	company: Building2,
	library: Library,
	academic: Library,
	shield: Shield,
	roles: Shield,
	security: Shield,
	permission: Shield,
	menu: MenuIcon,
	file: File,
	folder: Folder,
	link: LinkIcon,
	
	// Academic & Education
	'graduation-cap': GraduationCap,
	graduationCap: GraduationCap,
	education: GraduationCap,
	'user-graduate': GraduationCap, // Map user-graduate to graduation-cap
	userGraduate: GraduationCap,
	calendar: Calendar,
	'calendar-days': CalendarDays,
	calendarDays: CalendarDays,
	year: Calendar,
	semester: CalendarDays,
	clock: Clock,
	time: Clock,
	schedule: Clock,
	
	// Documents & Files
	'file-text': FileText,
	fileText: FileText,
	document: FileText,
	report: FileText,
	archive: Archive,
	
	// Communication
	mail: Mail,
	email: Mail,
	phone: Phone,
	'message-circle': MessageCircle,
	messageCircle: MessageCircle,
	chat: MessageCircle,
	message: MessageCircle,
	'message-square': MessageSquare,
	messageSquare: MessageSquare,
	
	// Location & Navigation
	'map-pin': MapPin,
	mapPin: MapPin,
	location: MapPin,
	address: MapPin,
	map: Map,
	navigation: Navigation,
	compass: Compass,
	
	// Actions
	plus: Plus,
	add: Plus,
	edit: Edit,
	'trash-2': Trash2,
	trash2: Trash2,
	delete: Trash2,
	remove: Trash2,
	save: Save,
	x: X,
	close: X,
	cancel: X,
	check: Check,
	confirm: Check,
	success: Check,
	search: Search,
	filter: Filter,
	
	// Status & Alerts
	'alert-circle': AlertCircle,
	alertCircle: AlertCircle,
	alert: AlertCircle,
	warning: AlertCircle,
	error: AlertCircle,
	info: Info,
	information: Info,
	'help-circle': HelpCircle,
	helpCircle: HelpCircle,
	help: HelpCircle,
	question: HelpCircle,
	
	// Media & Content
	eye: Eye,
	view: Eye,
	visible: Eye,
	'eye-off': EyeOff,
	eyeOff: EyeOff,
	hidden: EyeOff,
	invisible: EyeOff,
	image: Image,
	photo: Image,
	picture: Image,
	video: Video,
	music: Music,
	audio: Music,
	play: Play,
	pause: Pause,
	
	// Interaction
	download: Download,
	upload: Upload,
	share: Share,
	copy: Copy,
	bookmark: Bookmark,
	tag: Tag,
	bell: Bell,
	notification: Bell,
	activity: Activity,
	'trending-up': TrendingUp,
	trendingUp: TrendingUp,
	trending: TrendingUp,
	growth: TrendingUp,
	
	// Achievement & Status
	award: Award,
	achievement: Award,
	trophy: Award,
	target: Target,
	goal: Target,
	objective: Target,
	zap: Zap,
	power: Zap,
	energy: Zap,
	star: Star,
	favorite: Star,
	rating: Star,
	heart: Heart,
	like: Heart,
	love: Heart,
	
	// Layout & Organization
	layers: Layers,
	stack: Layers,
	grid: Grid,
	layout: Grid,
	list: List,
	items: List,
	inbox: Inbox,
	send: Send,
	
	// Technology & Devices
	monitor: Monitor,
	desktop: Monitor,
	computer: Monitor,
	smartphone: Smartphone,
	mobile: Smartphone,
	tablet: Tablet,
	laptop: Laptop,
	server: Server,
	database: Database,
	cloud: Cloud,
	storage: Cloud,
	
	// Security & Access
	lock: Lock,
	locked: Lock,
	secure: Lock,
	unlock: Unlock,
	unlocked: Unlock,
	key: Key,
	password: Key,
	'log-in': LogIn,
	logIn: LogIn,
	login: LogIn,
	signin: LogIn,
	'log-out': LogOut,
	logOut: LogOut,
	logout: LogOut,
	signout: LogOut,
	'user-plus': UserPlus,
	userPlus: UserPlus,
	addUser: UserPlus,
	'user-minus': UserMinus,
	userMinus: UserMinus,
	removeUser: UserMinus,
	'user-x': UserX,
	userX: UserX,
	deleteUser: UserX,
	'user-check': UserCheck,
	userCheck: UserCheck,
	approveUser: UserCheck,
	
	// Commerce & Finance
	'credit-card': CreditCard,
	creditCard: CreditCard,
	card: CreditCard,
	payment: CreditCard,
	'dollar-sign': DollarSign,
	dollarSign: DollarSign,
	money: DollarSign,
	currency: DollarSign,
	price: DollarSign,
	'shopping-cart': ShoppingCart,
	shoppingCart: ShoppingCart,
	cart: ShoppingCart,
	package: Package,
	box: Package,
	product: Package,
	truck: Truck,
	delivery: Truck,
	shipping: Truck,
	
	// Connectivity & Network
	wifi: Wifi,
	'wifi-off': WifiOff,
	wifiOff: WifiOff,
	offline: WifiOff,
	globe: Globe,
	internet: Globe,
	web: Globe,
	website: Globe,
	
	// Hardware & System
	battery: Battery,
	'battery-low': BatteryLow,
	batteryLow: BatteryLow,
	bluetooth: Bluetooth,
	camera: Camera,
	mic: Mic,
	microphone: Mic,
	'mic-off': MicOff,
	micOff: MicOff,
	mute: MicOff,
	'volume-2': Volume2,
	volume2: Volume2,
	sound: Volume2,
	'volume-x': VolumeX,
	volumeX: VolumeX,
	silent: VolumeX,
	
	// Time & Schedule
	timer: Timer,
	
	// Weather & Environment
	sun: Sun,
	sunny: Sun,
	day: Sun,
	moon: Moon,
	night: Moon,
	'cloud-drizzle': CloudDrizzle,
	cloudDrizzle: CloudDrizzle,
	drizzle: CloudDrizzle,
	'cloud-rain': CloudRain,
	cloudRain: CloudRain,
	rain: CloudRain,
	'cloud-snow': CloudSnow,
	cloudSnow: CloudSnow,
	snow: CloudSnow,
	wind: Wind,
	air: Wind,
	thermometer: Thermometer,
	temperature: Thermometer,
	umbrella: Umbrella,
	snowflake: Snowflake,
	
	// Navigation & Direction
	flag: Flag,
	marker: Flag,
	'chevron-right': ChevronRight,
	chevronRight: ChevronRight,
	right: ChevronRight,
	next: ChevronRight,
}

// Function to get icon component by name
export const getIconByName = (iconName: string | undefined): LucideIcon => {
	if (!iconName) return File // Default fallback icon
	
	// Try exact match first
	if (iconMap[iconName]) {
		return iconMap[iconName]
	}
	
	// Try lowercase
	const lowerName = iconName.toLowerCase()
	if (iconMap[lowerName]) {
		return iconMap[lowerName]
	}
	
	// Try kebab-case to camelCase conversion
	const camelName = iconName.replace(/-([a-z])/g, (g) => g[1].toUpperCase())
	if (iconMap[camelName]) {
		return iconMap[camelName]
	}
	
	// Try camelCase to kebab-case conversion
	const kebabName = iconName.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
	if (iconMap[kebabName]) {
		return iconMap[kebabName]
	}
	
	// Return default icon if not found
	console.warn(`Icon "${iconName}" not found, using default File icon`)
	return File
}

// Component to render dynamic icon
export function DynamicIcon({ 
	name, 
	className, 
	size = 16,
	...props 
}: { 
	name: string | undefined
	className?: string
	size?: number
} & React.ComponentProps<LucideIcon>) {
	const IconComponent = getIconByName(name)
	return <IconComponent className={className} size={size} {...props} />
}
