export { LecturerList } from './LecturerList'
export { LecturerForm } from './LecturerForm'
export { LecturerDetails } from './LecturerDetails'
export { LecturersContainer } from './LecturersContainer'
export { LecturerDeletedList } from './LecturerDeletedList'